export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


import { CssBaseline, GlobalStyles } from "@mui/material";
import { Providers } from "./providers";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Inter font from Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <CssBaseline />
        <GlobalStyles styles={{ body: { fontFamily: "'Inter', system-ui, sans-serif" } }} />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
